account_id = ""
name = "xdnmb-watcher-dev"
workers_dev = true
main = "./dist/main.js"
compatibility_date = "2023-08-07"

kv_namespaces = [
  #   { binding = "KV", id = "", preview_id = "" }
  # Don't bind __STATIC_CONTENT here. It will be bound automatically.
]

[triggers]
crons = ["*/1 * * * *"]

[build]
command = "webpack"

[site]
bucket = "./public"
entry-point = "./"

# Global variables can be used by the Worker scripts.
# NOT inherited. Need to define in each environment.
[vars]
NOTIFIER = "telegram" # Now only support telegram
PARSE_URL = "" # can be set to "https://inkrssparse.vercel.app" with fair use
SECRET_PATH = "" 

# Bark notification
BARK_URL = ""

# Telegram notification
TELEGRAPH_TOKEN = ""
TG_TOKEN = ""

TG_SENDID = 123456789 # OR "@channel_name"
TG_USERID = 123456789 

# WeChat notification
WECHAT_URL = ""

# XDNMB Cookie. Value of "userhash" in cookie.
COOKIES = ""

# # Environments / Multiple Workers
# # Ref: https://developers.cloudflare.com/workers/platform/environments

# [env.production]
# name = "xdnmb-watcher"
# # workers_dev = false
# # route = ""
# # zone_id = ""
# kv_namespaces = [
#   #   { binding = "KV", id = "" }
# ]

# [env.production.vars]
# NOTIFIER = "telegram" # bark, telegram or wechat

# PARSE_URL = ""
# SECRET_PATH = ""

# # Telegram notification
# TELEGRAPH_TOKEN = ""
# TG_TOKEN = ""

# TG_SENDID = 123456789 # OR "@channel_name"
# TG_USERID = 123456789
